# Generated by Django 3.0.2 on 2020-02-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywordName', models.CharField(max_length=200)),
                ('isAliasFor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Keyword')),
            ],
        ),
    ]
