# Generated by Django 3.0.2 on 2020-02-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200220_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='higherLevelSkill',
            field=models.ManyToManyField(related_name='_skill_higherLevelSkill_+', to='content.Skill'),
        ),
    ]
