# Generated by Django 3.0.2 on 2020-02-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_skill_higherlevelskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='higherLevelSkill',
            field=models.ManyToManyField(blank=True, null=True, related_name='_skill_higherLevelSkill_+', to='content.Skill'),
        ),
    ]
