# Generated by Django 3.0.2 on 2020-02-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200220_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='higherLevelSkill',
        ),
    ]
