# Generated by Django 3.0.2 on 2020-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_skill_higherlevelskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentName', models.CharField(max_length=200)),
                ('binaryContent', models.FileField(upload_to='content/%Y/%m/%d/')),
                ('newSkills', models.ManyToManyField(blank=True, null=True, related_name='skills_new', to='content.Skill')),
                ('requiredSkills', models.ManyToManyField(blank=True, null=True, related_name='skills_required', to='content.Skill')),
            ],
        ),
    ]
