# Generated by Django 3.0.2 on 2020-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='newSkills',
            field=models.ManyToManyField(blank=True, related_name='skills_new', to='content.Skill'),
        ),
        migrations.AlterField(
            model_name='content',
            name='requiredSkills',
            field=models.ManyToManyField(blank=True, related_name='skills_required', to='content.Skill'),
        ),
    ]
