# Generated by Django 3.0.2 on 2020-02-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200221_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='contentDescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
