# Generated by Django 3.0.2 on 2020-02-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20200225_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ManyToManyField(blank=True, to='content.Category'),
        ),
    ]
