# Generated by Django 3.0.6 on 2020-05-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20200520_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skillName',
            new_name='skill_name',
        ),
    ]
