# Generated by Django 3.0.6 on 2020-05-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20200520_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='contentName',
            new_name='content_name',
        ),
    ]
