# Generated by Django 3.0.6 on 2020-05-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20200520_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='binaryContent',
            new_name='binary_content',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='contentDescription',
            new_name='content_description',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='newSkills',
            new_name='new_skills',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='requiredSkills',
            new_name='required_skills',
        ),
    ]
