# Generated by Django 3.0.6 on 2020-07-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20200520_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_workload',
            field=models.FloatField(default=0.0),
        ),
    ]
