# Generated by Django 3.0.6 on 2020-07-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_content_content_workload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_workload',
            field=models.FloatField(default=0.0, help_text='minutes'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('module_description', models.TextField()),
                ('module_content_modules', models.ManyToManyField(blank=True, to='content.Content')),
            ],
        ),
    ]
