# Generated by Django 3.0.6 on 2020-07-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20200708_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='LinkProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.TextField(blank=True)),
                ('content_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_start', to='content.Content')),
                ('content_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_target', to='content.Content')),
                ('link_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Skill')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
