# Generated by Django 3.0.6 on 2020-07-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_remove_skill_is_alias_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_descriptive_keywords',
            field=models.TextField(blank=True, help_text='comma separated keywords'),
        ),
    ]
