# Generated by Django 3.0.6 on 2020-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_skill_skill_descriptive_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_descriptive_keywords',
            field=models.TextField(blank=True, help_text='Space separated keywords for searching the skill.'),
        ),
    ]
