# Generated by Django 3.0.6 on 2020-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20200825_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['keyword_name'],
            },
        ),
    ]
