# Generated by Django 3.0.6 on 2020-09-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20200915_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stored_data', models.TextField()),
                ('storage_name', models.CharField(max_length=100)),
            ],
        ),
    ]
