# Generated by Django 3.0.6 on 2020-09-16 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0026_storedconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedconfiguration',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='storedconfiguration',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
