# Generated by Django 3.0.6 on 2020-10-19 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20200916_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikidataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.TextField(help_text='The wikidata item id', validators=[django.core.validators.RegexValidator('^Q([1-9][0-9]*)$', message='Invalid format. Should be Q<number>.')])),
            ],
        ),
    ]
