# Generated by Django 3.0.6 on 2020-10-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20201019_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikidataentry',
            name='wikidata_last_query',
            field=models.TextField(blank=True, help_text='last query'),
        ),
    ]
