# Generated by Django 3.0.6 on 2020-10-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_wikidataentry_wikidata_last_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikidataentry',
            name='wikidata_last_query',
        ),
        migrations.AddField(
            model_name='wikidataentry',
            name='wikidata_related_fields_raw',
            field=models.TextField(blank=True, help_text='Related fields according to wikidata'),
        ),
    ]
