# Generated by Django 3.0.6 on 2021-03-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_configkeyvaluestorage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-id'], 'permissions': (('skill_manager', 'Manage Skills'),)},
        ),
    ]
