# Generated by Django 3.0.6 on 2021-03-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20210312_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-id'], 'permissions': (('content_manager', 'Manage Content Items'),)},
        ),
    ]
