# Generated by Django 3.0.6 on 2021-03-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_auto_20210312_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='keyword_related_wikidata',
            field=models.ManyToManyField(blank=True, help_text='Related wikidata fields in this installation.', to='content.WikidataEntry'),
        ),
    ]
