# Generated by Django 3.0.6 on 2021-03-14 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0039_keyword_keyword_related_wikidata'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added this content', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Is this content visible to all users.'),
        ),
    ]
