# Generated by Django 3.0.6 on 2021-03-14 18:26

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_auto_20210314_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url_content',
            field=models.URLField(blank=True, help_text='URL of related content.', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='binary_content',
            field=models.FileField(blank=True, help_text='binary content like a file or a video.', null=True, upload_to=content.models.getFilePath),
        ),
    ]
