# Generated by Django 3.0.6 on 2021-03-21 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_auto_20210314_1826'),
    ]

    operations = [
        migrations.RenameModel("WikidataEntry", "WikidataKeyword"),
        migrations.AlterField(
            model_name='keyword',
            name='keyword_related_wikidata',
            field=models.ManyToManyField(blank=True, help_text='Related wikidata fields in this installation.', to='content.WikidataKeyword'),
        ),
    ]
