# Generated by Django 3.0.6 on 2021-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_auto_20210321_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_keywords',
            field=models.ManyToManyField(blank=True, related_name='content_keyword', to='content.WikidataKeyword'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_keywords',
            field=models.ManyToManyField(blank=True, related_name='skill_keyword', to='content.WikidataKeyword'),
        ),
    ]
