# Generated by Django 3.0.6 on 2021-03-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_auto_20210321_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
