# Generated by Django 3.2 on 2021-07-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_delete_keyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikidatakeyword',
            options={'ordering': ['wikidata_name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_descriptive_keywords',
        ),
    ]
